import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { AuthService } from './auth.service';
import { MockDataService, Owner, Ride } from './mock-data.service';
import { ToastService } from './toast.service';
import { DiditReviewDetailComponent } from './components/didit-review-detail.component';

type AdminModule='subscriptions'|'users'|'rides'|'tickets'|'didit';
@Component({
 selector:'app-admin-module',standalone:true,imports:[CommonModule,FormsModule,RouterLink,DiditReviewDetailComponent],
 template:`
 <main class="workspace">
    <header><div><p>{{ eyebrow }}</p><h1>{{ title }}</h1><span>{{ description }}</span></div><div class="header-actions"><a routerLink="/Kumaresh/dashboard">Back to dashboard</a><button type="button" (click)="load()">Refresh</button></div></header>
  <section class="panel" *ngIf="module==='subscriptions'">
   <div class="toolbar"><div><h2>Payment ledger</h2><small>{{filteredSubscriptions.length}} records</small></div><div class="filters"><select [(ngModel)]="filter"><option value="">All statuses</option><option value="VERIFICATION_IN_PROGRESS">Awaiting review</option><option value="PAID">Approved</option><option value="REJECTED">Rejected</option><option value="INACTIVE">Inactive</option></select><button (click)="download()">Export CSV</button></div></div>
  <div class="table"><table><thead><tr><th>Owner</th><th>Amount</th><th>Plan</th><th>UTR</th><th>Status</th><th>Action</th></tr></thead><tbody><tr *ngFor="let item of filteredSubscriptions"><td><strong>{{item.ownerName}}</strong><small>{{item.ownerMobile}}</small></td><td>₹{{item.amount/100}}</td><td>{{item.planName||'—'}}</td><td><code>{{item.utrNumber||'—'}}</code></td><td><span class="status" [attr.data-status]="item.status">{{label(item.status)}}</span></td><td class="actions"><button *ngIf="isSubscriptionPending(item.status)" (click)="approveSubscription(item.id)">Approve</button><button class="danger" *ngIf="isSubscriptionPending(item.status)" (click)="rejectSubscription(item.id)">Reject</button></td></tr></tbody></table></div>
  </section>
  <section class="panel" *ngIf="module==='users'">
    <div class="toolbar"><div><h2>User accounts</h2><small>{{filteredUsers.length}} records</small></div><div class="filters"><input [(ngModel)]="query" placeholder="Search name or mobile"><select [(ngModel)]="filter"><option value="">All roles</option><option value="OWNER">Owners</option><option value="PASSENGER">Passengers</option></select></div></div>
    <div class="table"><table><thead><tr><th>Name</th><th>Role</th><th>Mobile</th><th>Gender</th><th>Mobile</th><th>Identity</th><th>Account</th><th>Joined</th></tr></thead><tbody><tr *ngFor="let item of filteredUsers"><td><strong>{{item.name}}</strong><small>{{item.id}}</small></td><td>{{item.role}}</td><td>{{item.mobile}}</td><td>{{item.gender||'—'}}</td><td>{{item.mobileVerified?'Verified':'Pending'}}</td><td><span class="status" [attr.data-status]="item.verificationStatus">{{label(item.verificationStatus)}}</span></td><td>{{item.active?'Active':'Inactive'}}</td><td>{{item.createdAt|date:'mediumDate'}}</td></tr></tbody></table></div>
  </section>
  <section class="panel" *ngIf="module==='rides'">
   <div class="toolbar"><div><h2>Ride inventory</h2><small>{{filteredRides.length}} records</small></div><select [(ngModel)]="filter"><option value="">All statuses</option><option value="active">Active</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></div>
   <div class="table"><table><thead><tr><th>Owner</th><th>Route</th><th>Date</th><th>Seats</th><th>Female only</th><th>Status</th></tr></thead><tbody><tr *ngFor="let item of filteredRides"><td>{{item.ownerId}}</td><td><strong>{{item.from}} → {{item.to}}</strong><small>{{item.carModel}}</small></td><td>{{item.date}}<small>{{item.startTime}}–{{item.endTime}}</small></td><td>{{item.seatsAvailable}}</td><td>{{item.femaleOnly?'Yes':'No'}}</td><td><span class="status" [attr.data-status]="item.status">{{item.status}}</span></td></tr></tbody></table></div>
  </section>
  <section class="panel" *ngIf="module==='tickets'">
   <div class="toolbar"><div><h2>Support queue</h2><small>{{tickets.length}} records</small></div><select [(ngModel)]="filter" (change)="loadTickets()"><option value="">All statuses</option><option value="PENDING">Pending</option><option value="RESOLVED">Resolved</option></select></div>
   <div class="table"><table><thead><tr><th>User</th><th>Category</th><th>Description</th><th>Priority</th><th>Status</th><th>Action</th></tr></thead><tbody><tr *ngFor="let item of tickets"><td><strong>{{item.userName||item.userMobile}}</strong></td><td>{{item.categoryLabel||item.category}}</td><td class="description">{{item.description}}</td><td><span class="status" [attr.data-status]="item.priority">{{item.priority||'NORMAL'}}</span></td><td><span class="status" [attr.data-status]="item.status">{{item.status}}</span></td><td><button *ngIf="item.status!=='RESOLVED'" (click)="resolveTicket(item)">Resolve</button></td></tr></tbody></table></div>
  </section>
  <section class="panel" *ngIf="module==='didit'">
   <div class="notice"><strong>Provider synchronized</strong><span>Approve and reject actions update Didit first, then CarShare247. Sessions must already be in a reviewable Didit state.</span></div>
   <div class="toolbar"><div><h2>Identity verification queue</h2><small>{{verifications.length}} records</small></div><select [(ngModel)]="filter"><option value="">All statuses</option><option value="IN_REVIEW">In review</option><option value="APPROVED">Approved</option><option value="REJECTED">Rejected</option></select></div>
   <div class="table"><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Session</th><th>Submitted</th><th>Action</th></tr></thead><tbody><tr *ngFor="let item of filteredVerifications"><td><strong>{{item.userName||'Unknown user'}}</strong><small>{{item.userId}}</small></td><td>{{item.userRole}}</td><td><span class="status" [attr.data-status]="normalizedStatus(item.status)">{{normalizedStatus(item.status)}}</span></td><td><code>{{item.sessionId}}</code></td><td>{{item.createdAt|date:'medium'}}</td><td class="actions"><button (click)="selectedReview=item">Review</button><button *ngIf="normalizedStatus(item.status)==='IN_REVIEW'" (click)="approveDidit(item)">Approve</button><button class="danger" *ngIf="normalizedStatus(item.status)==='IN_REVIEW'" (click)="rejectDidit(item)">Reject</button></td></tr></tbody></table></div>
  </section>
  <div class="empty" *ngIf="!loading && rowCount===0">No records found for this workspace.</div>
  <app-didit-review-detail *ngIf="selectedReview" [review]="selectedReview" (close)="selectedReview=null" (decision)="diditDecision($event)"></app-didit-review-detail>
 </main>`,
 styles:[`
 :host{display:block}.workspace{max-width:1220px;margin:auto;padding:28px 0 56px;color:#172033}header{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:20px}header p{margin:0 0 5px;color:#087b6c;font-size:.72rem;font-weight:900;letter-spacing:.12em}header h1{margin:0;font-size:clamp(1.8rem,4vw,2.8rem);letter-spacing:0}header span{display:block;margin-top:6px;color:#617083}.header-actions{display:flex;gap:8px}.header-actions a,button{min-height:40px;border:1px solid #cbd6dc;background:#fff;color:#172033;border-radius:6px;padding:0 12px;cursor:pointer;font-weight:700;text-decoration:none;display:inline-flex;align-items:center;justify-content:center}.panel{border:1px solid #dce4e8;border-radius:8px;background:#fff;overflow:hidden}.toolbar{display:flex;justify-content:space-between;align-items:center;gap:14px;padding:16px;border-bottom:1px solid #e4e9ec}.toolbar h2{margin:0 0 3px;font-size:1.1rem}.toolbar small,td small{display:block;color:#617083;margin-top:4px}.filters{display:flex;gap:8px}input,select{min-height:40px;border:1px solid #cbd6dc;border-radius:6px;padding:0 10px}.table{overflow:auto}table{width:100%;border-collapse:collapse;min-width:860px}th,td{text-align:left;padding:13px 15px;border-bottom:1px solid #e7ecef;vertical-align:top}th{background:#f7f9fa;color:#617083;font-size:.72rem;text-transform:uppercase}td{font-size:.88rem}.description{max-width:300px}.actions{display:flex;gap:6px}.danger{border-color:#e8b1b1;color:#9d2020}.status{display:inline-block;padding:4px 7px;border-radius:4px;background:#eaf0f3;font-size:.73rem;font-weight:800;text-transform:uppercase}.status[data-status=APPROVED],.status[data-status=PAID],.status[data-status=RESOLVED],.status[data-status=ACTIVE]{background:#d9f5e8;color:#086844}.status[data-status=IN_REVIEW],.status[data-status=VERIFICATION_IN_PROGRESS],.status[data-status=PENDING]{background:#fff0c2;color:#785500}.status[data-status=REJECTED],.status[data-status=DECLINED],.status[data-status=CANCELLED],.status[data-status=URGENT]{background:#fde1e1;color:#962525}.notice{display:grid;gap:3px;margin:0 0 12px;padding:12px 14px;border-left:3px solid #087b6c;background:#edf8f5;color:#31534e}.notice span{font-size:.85rem}.empty{text-align:center;padding:32px;color:#617083}@media(max-width:760px){.workspace{padding:16px 0 40px}header{align-items:flex-start;flex-direction:column}.header-actions{width:100%}.header-actions a,.header-actions button{flex:1}.toolbar{align-items:stretch;flex-direction:column}.filters{flex-direction:column}}
 `]
})
export class AdminModuleComponent {
 module:AdminModule='subscriptions'; loading=false; filter=''; query=''; subscriptions:any[]=[]; users:any[]=[]; rides:Ride[]=[]; tickets:any[]=[]; verifications:any[]=[]; selectedReview:any=null;
 readonly meta:Record<AdminModule,{title:string;description:string;eyebrow:string}>={subscriptions:{title:'Subscriptions',description:'Review payments and maintain the owner subscription ledger.',eyebrow:'PAYMENTS'},users:{title:'Users',description:'Inspect registered owner accounts and verification state.',eyebrow:'ACCOUNTS'},rides:{title:'Rides',description:'Monitor ride inventory and operating status.',eyebrow:'OPERATIONS'},tickets:{title:'Support tickets',description:'Triage support requests and record clear resolutions.',eyebrow:'SUPPORT'},didit:{title:'Didit verification',description:'Review identity sessions and synchronize decisions with Didit.',eyebrow:'IDENTITY'}};
 constructor(private route:ActivatedRoute,private router:Router,private auth:AuthService,private data:MockDataService,private toast:ToastService){if(auth.current?.role!=='admin'){void router.navigateByUrl('/Kumaresh');return;}this.module=(route.snapshot.data['module']||'subscriptions') as AdminModule;this.load();}
 get title(){return this.meta[this.module].title}get description(){return this.meta[this.module].description}get eyebrow(){return this.meta[this.module].eyebrow}
 get filteredSubscriptions(){return this.filter?this.subscriptions.filter(x=>x.status===this.filter):this.subscriptions}
 get filteredUsers(){const q=this.query.toLowerCase();return this.users.filter(x=>(!this.filter||x.role===this.filter)&&JSON.stringify(x).toLowerCase().includes(q))}
 get filteredRides(){return this.filter?this.rides.filter(x=>String(x.status).toLowerCase()===this.filter):this.rides}
 get filteredVerifications(){return this.filter?this.verifications.filter(x=>this.normalizedStatus(x.status)===this.filter):this.verifications}
 get rowCount(){return this.module==='subscriptions'?this.filteredSubscriptions.length:this.module==='users'?this.filteredUsers.length:this.module==='rides'?this.filteredRides.length:this.module==='tickets'?this.tickets.length:this.filteredVerifications.length}
 isSubscriptionPending(status:string){return ['PENDING','VERIFICATION_IN_PROGRESS'].includes(String(status||'').toUpperCase())}
 load(){this.loading=true;if(this.module==='subscriptions')this.data.getAdminSubscriptions('').subscribe({next:x=>{this.subscriptions=x||[];this.loading=false},error:()=>this.failed()});if(this.module==='users')this.data.getAdminUsers().subscribe({next:x=>{this.users=x||[];this.loading=false},error:()=>this.failed()});if(this.module==='rides')this.data.getAdminRides().subscribe({next:x=>{this.rides=x||[];this.loading=false},error:()=>this.failed()});if(this.module==='tickets')this.loadTickets();if(this.module==='didit')this.data.getAdminDiditVerifications().subscribe({next:x=>{this.verifications=this.latestDiditSessions(x||[]);this.loading=false},error:()=>this.failed()});}
 loadTickets(){this.loading=true;this.data.getAdminTickets(this.filter).subscribe({next:x=>{this.tickets=x||[];this.loading=false},error:()=>this.failed()})}
 failed(){this.loading=false;this.toast.show(`Unable to load ${this.title.toLowerCase()}`,'error')}
 label(value:string){return value==='VERIFICATION_IN_PROGRESS'?'Awaiting review':String(value||'').replaceAll('_',' ')}
 normalizedStatus(value:string){const status=String(value||'').toUpperCase();if(['PENDING_VERIFICATION','INITIATED','IN_REVIEW','UNDER_REVIEW'].includes(status))return'IN_REVIEW';if(['VERIFIED','APPROVED'].includes(status))return'APPROVED';if(['REJECTED','DECLINED'].includes(status))return'REJECTED';return status}
 approveSubscription(id:string){this.data.approveSubscription(id).subscribe({next:()=>{this.toast.show('Subscription approved','success');this.load()},error:e=>this.apiError(e,'Approval failed')})}
 rejectSubscription(id:string){const note=prompt('Enter rejection reason');if(note?.trim())this.data.rejectSubscription(id,note.trim()).subscribe({next:()=>{this.toast.show('Subscription rejected','success');this.load()},error:e=>this.apiError(e,'Rejection failed')})}
 download(){this.data.exportSubscriptions().subscribe(blob=>{const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download='subscription-audit.csv';anchor.click();URL.revokeObjectURL(url)})}
 viewOwner(id:string){void this.router.navigate(['/owner',id])}
 resolveTicket(item:any){const note=prompt('Enter resolution details');if(note?.trim())this.data.resolveTicket(item.id,note.trim()).subscribe({next:()=>{this.toast.show('Ticket resolved','success');this.loadTickets()},error:e=>this.apiError(e,'Unable to resolve ticket')})}
 approveDidit(item:any,comment='Approved after manual compliance review.'){this.data.approveDiditReview(item.sessionId||item.id,comment).subscribe({next:()=>{this.toast.show('Didit verification approved','success');this.selectedReview=null;this.load()},error:e=>this.apiError(e,'Didit approval failed')})}
 rejectDidit(item:any,reason?:string){const note=reason||prompt('Enter rejection reason')||'';if(!note.trim())return;this.data.rejectDiditReview(item.sessionId||item.id,note.trim()).subscribe({next:()=>{this.toast.show('Didit verification rejected','success');this.selectedReview=null;this.load()},error:e=>this.apiError(e,'Didit rejection failed')})}
 diditDecision(event:{action:'APPROVE'|'REJECT';comment:string}){if(!this.selectedReview)return;event.action==='APPROVE'?this.approveDidit(this.selectedReview,event.comment):this.rejectDidit(this.selectedReview,event.comment)}
 private latestDiditSessions(rows:any[]):any[]{const sessions=new Map<string,any>();[...rows].sort((left,right)=>new Date(right.updatedAt||right.createdAt||0).getTime()-new Date(left.updatedAt||left.createdAt||0).getTime()).forEach(item=>{const key=String(item.sessionId||item.id);if(!sessions.has(key))sessions.set(key,item)});return [...sessions.values()]}
 private apiError(error:any,fallback:string){this.toast.show(error?.error?.error?.message||error?.error?.message||fallback,'error')}
}
